#!/usr/bin/env node
/**
 * JARVIS Quick Setup Script
 * Run: node setup.js
 */

import { exec } from 'child_process';
import { promisify } from 'util';
import fs from 'fs';
import readline from 'readline';

const execAsync = promisify(exec);

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
});

const ask = (question) => new Promise((resolve) => rl.question(question, resolve));

console.log(`
╔══════════════════════════════════════════╗
║        JARVIS Setup Wizard               ║
║     Let's configure your assistant       ║
╚══════════════════════════════════════════╝
`);

async function setup() {
  try {
    // User preferences
    console.log('\n📋 Basic Configuration\n');

    const userName = await ask('What should JARVIS call you? (e.g., Sir, Boss, [Your Name]): ');
    const voiceEnabled = await ask('Enable voice output? (y/n): ');
    const pcControl = await ask('Allow PC control? (y/n): ');
    const systemCommands = await ask('Allow system commands (shutdown/restart)? (y/n): ');
    const debugMode = await ask('Enable debug mode? (y/n): ');

    // Generate .env file
    const envContent = `# JARVIS AI Assistant Configuration
# Generated by setup.js on ${new Date().toISOString()}

# System
APP_NAME=JARVIS
VERSION=1.0.0
USER_NAME=${userName || 'Sir'}
DEBUG=${debugMode.toLowerCase() === 'y' ? 'true' : 'false'}

# Voice
VOICE_ENABLED=${voiceEnabled.toLowerCase() === 'y' ? 'true' : 'false'}
TTS_ENGINE=native
RECOGNITION_LANGUAGE=en-US

# PC Control
PC_CONTROL_ENABLED=${pcControl.toLowerCase() === 'y' ? 'true' : 'false'}
ALLOW_SYSTEM_COMMANDS=${systemCommands.toLowerCase() === 'y' ? 'true' : 'false'}
SCREENSHOT_DIR=./screenshots

# Memory
MEMORY_ENABLED=true
MAX_CONVERSATIONS=1000
AUTO_SAVE_INTERVAL=300000

# Agents
AGENT_TIMEOUT=30000
MAX_CONCURRENT_AGENTS=5

# Security
REQUIRE_AUTHENTICATION=false
LOG_SENSITIVE_DATA=false

# Logging
LOG_LEVEL=info
LOG_TO_FILE=true
`;

    fs.writeFileSync('.env', envContent);
    console.log('\n✅ Configuration saved to .env');

    // Create necessary directories
    const dirs = ['.jarvis-data', '.jarvis-logs', 'screenshots'];
    for (const dir of dirs) {
      if (!fs.existsSync(dir)) {
        fs.mkdirSync(dir, { recursive: true });
        console.log(`✅ Created directory: ${dir}`);
      }
    }

    // Install dependencies
    console.log('\n📦 Installing dependencies...');
    try {
      await execAsync('npm install', { timeout: 120000 });
      console.log('✅ Dependencies installed');
    } catch (error) {
      console.log('⚠️ Some dependencies may have failed to install. Run "npm install" manually.');
    }

    console.log(`
╔══════════════════════════════════════════╗
║           Setup Complete! 🎉             ║
╠══════════════════════════════════════════╣
║                                          ║
║  To start JARVIS:                        ║
║                                          ║
║  Windows:  double-click start-jarvis.bat ║
║     or     npm start                     ║
║                                          ║
║  Linux/Mac: bash start-jarvis.sh         ║
║     or      npm start                    ║
║                                          ║
╚══════════════════════════════════════════╝
    `);

  } catch (error) {
    console.error('Setup failed:', error.message);
  } finally {
    rl.close();
  }
}

setup();
